[package]
name = "rabbitmq"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-lite = "2.6.1"
lapin = "3.6.0"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
